#!/usr/bin/env python3
"""
Audit script for the Apache 2.0 license-header rule (γ-1b Stage 1).

Scans every Sources/**/*.swift file in the package for an Apache 2.0
license header. The header is required to appear in the first 30 lines.
Tests/**, Package.swift, and Package@*.swift are excluded.

Per research §3.4.3:
  Apache 2.0 header on every Sources/**/*.swift. No exemptions needed
  for L1 (verified: no generated files; no Sources/*Generated* paths;
  no // Generated by markers).

Empirical state (2026-05-04): L1 source files currently have NO Apache
2.0 headers. This Stage 1 (advisory) surface fires the ecosystem-wide
gap. Stage 2 codemod adds the header; Stage 3 flip removes the advisory
input from the calling site.

Header detection: case-insensitive substring "apache" AND "2.0" anywhere
in the first 30 lines (forgives variations like "Apache License, Version
2.0", "Apache License v2.0", "Apache-2.0", etc.).

Outputs (stdout): per-file findings, per-package summary.
Optional JSON output via --json <path>:

  {
    "package": "swift-X-primitives",
    "dir": "/path/to/package",
    "missing": ["Sources/X/Foo.swift", ...],
    "totals": {"missing": N, "files_scanned": K}
  }

Usage:
  audit-license-header.py --package-dir /path/to/package
  audit-license-header.py --package-dir . --json /tmp/audit.json
"""

import argparse
import json
import sys
from pathlib import Path

HEADER_LINE_LIMIT = 30
EXCLUDED_TOP_DIRS = {"Tests"}
EXCLUDED_NAMES = {"Package.swift"}


def has_apache_header(file_path: Path) -> bool:
    """Return True if the first HEADER_LINE_LIMIT lines mention Apache + 2.0."""
    try:
        with file_path.open("r", encoding="utf-8", errors="replace") as f:
            head = []
            for i, line in enumerate(f):
                if i >= HEADER_LINE_LIMIT:
                    break
                head.append(line)
    except OSError:
        return False
    blob = "".join(head).lower()
    return ("apache" in blob) and ("2.0" in blob)


def is_excluded(rel_path: Path) -> bool:
    parts = rel_path.parts
    if not parts:
        return True
    if parts[0] in EXCLUDED_TOP_DIRS:
        return True
    if rel_path.name in EXCLUDED_NAMES:
        return True
    if rel_path.name.startswith("Package@") and rel_path.name.endswith(".swift"):
        return True
    # Only audit Sources/** for now (Stage 1 scope per §3.4.3)
    if parts[0] != "Sources":
        return True
    return False


def audit_package(pkg_dir: Path) -> dict:
    pkg_dir = pkg_dir.resolve()
    missing: list[str] = []
    files_scanned = 0
    for swift_file in pkg_dir.rglob("*.swift"):
        try:
            rel_path = swift_file.relative_to(pkg_dir)
        except ValueError:
            continue
        if is_excluded(rel_path):
            continue
        files_scanned += 1
        if not has_apache_header(swift_file):
            missing.append(str(rel_path))
    return {
        "package": pkg_dir.name,
        "dir": str(pkg_dir),
        "missing": sorted(missing),
        "totals": {
            "missing": len(missing),
            "files_scanned": files_scanned,
        },
    }


def print_report(audit: dict) -> None:
    print("=" * 78)
    print("License-header audit (γ-1b Stage 1, advisory)")
    print("=" * 78)
    print(f"  Package:        {audit['package']}")
    print(f"  Directory:      {audit['dir']}")
    print(f"  Files scanned:  {audit['totals']['files_scanned']}")
    print(f"  Missing header: {audit['totals']['missing']}")
    print()
    if audit["missing"]:
        print("Files missing Apache 2.0 header:")
        for path in audit["missing"]:
            print(f"  - {path}")


def main() -> int:
    ap = argparse.ArgumentParser(description="License-header audit (γ-1b Stage 1)")
    ap.add_argument("--package-dir", type=Path, required=True,
                    help="Audit a single package at this path")
    ap.add_argument("--json", type=Path, help="Write raw findings to this JSON path")
    args = ap.parse_args()

    pkg_dir = args.package_dir.resolve()
    if not (pkg_dir / "Package.swift").is_file():
        print(f"error: {pkg_dir}/Package.swift not found", file=sys.stderr)
        return 2

    audit = audit_package(pkg_dir)
    print_report(audit)

    if args.json:
        args.json.write_text(json.dumps(audit, indent=2))
        print(f"\nJSON output written to {args.json}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
